import type { MutationFeedbackErrorOverride } from "@/shared/hooks/use-mutation-feedback-error";

export const onboardingErrorFeedbackOverride: MutationFeedbackErrorOverride = {
  validation: {
    title: "Revise os dados do onboarding.",
    message: "Alguns dados precisam de ajuste antes de concluir o cadastro inicial.",
  },
  unauthorized: {
    title: "Sua sessão expirou.",
    message: "Faça login novamente para concluir o onboarding.",
  },
  forbidden: {
    title: "Acesso negado ao onboarding.",
    message: "Seu usuário não tem permissão para concluir esse cadastro.",
  },
  notFound: {
    title: "Perfil de estabelecimento não encontrado.",
    message: "Não encontramos um perfil de estabelecimento para concluir o onboarding.",
  },
  conflict: {
    title: "Cadastro já encontrado.",
    message:
      "Alguns dados informados já estão cadastrados. Revise as informações e tente novamente.",
  },
  serverError: {
    title: "Não foi possível concluir o onboarding.",
    message: "O servidor não conseguiu concluir o cadastro inicial. Tente novamente em instantes.",
  },
  messages: [
    {
      statusCode: 400,
      match: "Invalid CNPJ:",
      title: "CNPJ inválido.",
      message: "Informe um CNPJ válido para concluir o onboarding.",
      field: "cnpj",
    },
    {
      statusCode: 400,
      match: "Invalid phone number:",
      title: "Telefone inválido.",
      message: "Informe um telefone válido para o cliente.",
      field: "customerPhone",
    },
    {
      statusCode: 400,
      match: "Invalid email address:",
      title: "E-mail inválido.",
      message: "Informe um e-mail válido para o cliente.",
      field: "customerEmail",
    },
    {
      statusCode: 400,
      match: "Service name cannot be empty",
      title: "Nome do serviço obrigatório.",
      message: "Informe o nome do serviço para concluir o onboarding.",
      field: "serviceName",
    },
    {
      statusCode: 400,
      match: "Service name should be shorter",
      title: "Nome do serviço muito longo.",
      message: "Use um nome de serviço com no máximo 72 caracteres.",
      field: "serviceName",
    },
    {
      statusCode: 400,
      match: "minInMinutes cannot be greater than maxInMinutes.",
      title: "Duração inválida.",
      message: "A duração mínima não pode ser maior que a duração máxima.",
      field: "minDurationInMinutes",
    },
    {
      statusCode: 400,
      match: "minInMinutes must be an integer.",
      title: "Duração mínima inválida.",
      message: "Informe a duração mínima como um número inteiro.",
      field: "minDurationInMinutes",
    },
    {
      statusCode: 400,
      match: "minInMinutes must be greater than zero.",
      title: "Duração mínima inválida.",
      message: "Informe uma duração mínima maior que zero.",
      field: "minDurationInMinutes",
    },
    {
      statusCode: 400,
      match: "maxInMinutes must be an integer.",
      title: "Duração máxima inválida.",
      message: "Informe a duração máxima como um número inteiro.",
      field: "maxDurationInMinutes",
    },
    {
      statusCode: 400,
      match: "maxInMinutes must be greater than zero.",
      title: "Duração máxima inválida.",
      message: "Informe uma duração máxima maior que zero.",
      field: "maxDurationInMinutes",
    },
    {
      statusCode: 400,
      match: "Amount must be an integer.",
      title: "Preço inválido.",
      message: "Informe um preço válido para o serviço.",
      field: "price",
    },
    {
      statusCode: 400,
      match: "Amount cannot be negative.",
      title: "Preço inválido.",
      message: "Informe um preço maior ou igual a zero.",
      field: "price",
    },
    {
      statusCode: 400,
      match: "plate must have exactly 7 chars.",
      title: "Placa inválida.",
      message: "Informe uma placa com exatamente 7 caracteres.",
      field: "vehiclePlate",
    },
    {
      statusCode: 400,
      match: "startsAt must be a valid date.",
      title: "Data de início inválida.",
      message: "Informe uma data de início válida para o agendamento.",
      field: "startsAt",
    },
    {
      statusCode: 400,
      match: "endsAt must be a valid date.",
      title: "Data de encerramento inválida.",
      message: "Informe uma data de encerramento válida para o agendamento.",
      field: "endsAt",
    },
    {
      statusCode: 400,
      match: "endsAt must be greater than startsAt.",
      title: "Período inválido.",
      message: "A data de encerramento deve ser posterior à data de início.",
      field: "endsAt",
    },
    {
      statusCode: 409,
      match: "Establishment already registered.",
      title: "Estabelecimento já cadastrado.",
      message: "Esse estabelecimento já foi cadastrado.",
      field: "cnpj",
    },
    {
      statusCode: 409,
      match: "Customer already registered.",
      title: "Cliente já cadastrado.",
      message: "Esse cliente já está cadastrado.",
      field: "customerPhone",
    },
    {
      statusCode: 409,
      match: "Vehicle already registered.",
      title: "Veículo já cadastrado.",
      message: "Esse veículo já está cadastrado.",
      field: "vehiclePlate",
    },
  ],
};
