import { BadgeCheck, CheckCircle2, Clock3, CircleX } from "lucide-react";

import type { KpiCardItem } from "@/shared/components/kpi-card";

import type { ListQuotesResponseDto } from "./types/quotes";

export const quotesPageMock: ListQuotesResponseDto = {
  quotes: [
    {
      id: "quote-2842",
      code: "2842",
      customerName: "Marcos Oliveira",
      customerKind: "CUSTOMER",
      vehicleLabel: "BMW X5 Black",
      vehiclePlate: "ABC-1234",
      totalInCents: 145000,
      status: "APPROVED",
      expiresAt: "2026-07-12T23:59:59.000Z",
      createdAt: "2026-06-21T13:45:00.000Z",
      servicesCount: 3,
    },
    {
      id: "quote-2841",
      code: "2841",
      customerName: "Ana Costa",
      customerKind: "PROSPECT",
      vehicleLabel: "Jeep Renegade White",
      vehiclePlate: "JKL-9088",
      totalInCents: 89000,
      status: "EXPIRES_TODAY",
      expiresAt: "2026-06-26T23:59:59.000Z",
      createdAt: "2026-06-24T09:20:00.000Z",
      servicesCount: 2,
    },
    {
      id: "quote-2840",
      code: "2840",
      customerName: "Ricardo Santos",
      customerKind: "CUSTOMER",
      vehicleLabel: "Audi A3 Blue",
      vehiclePlate: "XYZ-5511",
      totalInCents: 210000,
      status: "EXPIRED",
      expiresAt: "2026-06-18T23:59:59.000Z",
      createdAt: "2026-06-10T16:10:00.000Z",
      servicesCount: 4,
    },
    {
      id: "quote-2839",
      code: "2839",
      customerName: "Patricia Lima",
      customerKind: "CUSTOMER",
      vehicleLabel: "Fiat Pulse Red",
      vehiclePlate: "MNO-4433",
      totalInCents: 65000,
      status: "VALID",
      expiresAt: "2026-07-18T23:59:59.000Z",
      createdAt: "2026-06-19T11:35:00.000Z",
      servicesCount: 1,
    },
    {
      id: "quote-2838",
      code: "2838",
      customerName: "Bruno Almeida",
      customerKind: "PROSPECT",
      vehicleLabel: "Honda Civic Touring",
      vehiclePlate: "QWE-7744",
      totalInCents: 178000,
      status: "VALID",
      expiresAt: "2026-07-04T23:59:59.000Z",
      createdAt: "2026-06-23T14:05:00.000Z",
      servicesCount: 3,
    },
    {
      id: "quote-2837",
      code: "2837",
      customerName: "Carla Mendes",
      customerKind: "CUSTOMER",
      vehicleLabel: "Toyota Corolla Silver",
      vehiclePlate: "RTY-2026",
      totalInCents: 132000,
      status: "APPROVED",
      expiresAt: "2026-07-08T23:59:59.000Z",
      createdAt: "2026-06-20T10:25:00.000Z",
      servicesCount: 2,
    },
  ],
  totalItems: 32,
  summary: {
    valid: 24,
    expiresToday: 8,
    approved: 6,
    expired: 4,
  },
};

export const quotesPageKpisMock: KpiCardItem[] = [
  {
    id: "valid",
    label: "Validos",
    value: quotesPageMock.summary.valid,
    icon: CheckCircle2,
    description: "Dentro do prazo",
    tone: "success",
  },
  {
    id: "expires-today",
    label: "Vencem hoje",
    value: quotesPageMock.summary.expiresToday,
    icon: Clock3,
    description: "Prioridade do dia",
    tone: "warning",
  },
  {
    id: "expired",
    label: "Vencidos",
    value: quotesPageMock.summary.expired,
    icon: CircleX,
    description: "Fora do prazo",
    tone: "danger",
  },
  {
    id: "approved",
    label: "Aprovados",
    value: quotesPageMock.summary.approved,
    icon: BadgeCheck,
    description: "Convertidos",
    tone: "info",
  },
];
